apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: sample-deployment
  labels:
    env: dev
    type: DC 
spec:
  replicas: 3
  template: 
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: sample-container
        image: nginx
        ports:
        - containerPort: 80
