apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
  labels:
    service: load_balancer
spec:
  type: LoadBalancer
  ports:
  - port: 80 # Container port
    nodePort: 31333 # Host port
    protocol: TCP
  selector:
    app: my-app
