apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    service: my-service
spec:
  type: NodePort
  ports:
  - port: 80 # Container port
    nodePort: 32222 # Host port
    protocol: TCP
  selector:
    app: my-app
